### ISSUE TITLE
Example with svg string

### ISSUE THREAD

**Issue by ShivamJoker** [ahkohd/thumbo#4]
Hey thanks for building this cool library,
I was wondering if is it possible to convert svg XML string to png base64 in headless webworker or nodejs using this library

**Comment by ahkohd** [comment]
Hi @ShivamJoker,

Here is an example to answer your question. [View demo on Codesandbox](https://codesandbox.io/s/svg-text-png-base64-lk3p1)

**Comment by ShivamJoker** [comment]
Thanks a lot. But what would be equivalent of Filereader in Node to convert blob to base64?

I tried looking for some good solution but couldn't find.

**Comment by ShivamJoker** [comment]
Update: Converting blob to array buffer then to Buffer then .toString() seems to do the job.

Let me know if you have any better way.
